version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: js.Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      # - REACT_APP_API_URL=${REACT_APP_API_URL}
      - DANGEROUSLY_DISABLE_HOST_CHECK=true

networks:
  default:
    name: wasmiot-net
    driver: bridge
    external: true
